### ISSUE TITLE
Why an .init method?

### ISSUE THREAD

**Issue by lizmat** [CurtTilmes/raku-libgcrypt#1]
Why not make it an `INIT` block, so that it will get run whenever the program it is loaded in, starts executing.

**Comment by CurtTilmes** [comment]
Well my original reason was that you can't do it twice, and you can do it slightly differently.  If I INIT it, it is to late for anyone else to do it differently.

I switched it up a bit in v 0.3 to try to do the common case.

Of course one of the things you can do is configure secure memory, which I think it totally worthless once you interface with a VM that doesn't have secure memory, so I might just rip out that stuff and get rid of the init call, doing it in an `INIT`.  I can't really see anyone doing things too differently.

**Comment by CurtTilmes** [comment]
I'm going to do it -- get rid of some of the options that make no sense really for Raku, and just do INIT init.

**Comment by lizmat** [comment]
Why not get rid of the "init" method, and turn it into an INIT block?   :-)
