### ISSUE TITLE
Gcrypt install fails on centos

### ISSUE THREAD

**Issue by melezhik** [CurtTilmes/raku-libgcrypt#2]
Hi!

This is a report  http://repo.westus.cloudapp.azure.com/rakudist/reports/Gcrypt/centos/1586867428.txt

I can't say the certain reason of fails, as tests do not show much.

HTH

Alexey

PS Feel free to contact me, maybe I could run more low level debugging straight on docker instance ...

**Comment by melezhik** [comment]
speciously _this_ test just hangs:

```
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0  12012   404 pts/0    Ss+  Apr08   0:00 /bin/bash
cakinuy+  29045  0.0  0.3  52688 13268 ?        S    02:30   0:00 /usr/bin/perl -w /usr/bin/prove --ext .rakutest --ext .t --ext .t6 -r -e /tmp/whateverable/rakudo-moar/3aaca26a520eba9eba2cbd41168d4c509ac87bed/bin/rakudo t
cakinuy+  29054  0.4  2.5 593408 104268 ?       Sl   02:30   4:40 /tmp/whateverable/rakudo-moar/3aaca26a520eba9eba2cbd41168d4c509ac87bed/bin/rakudo t/01-basic.t
hgwrqwo+  31715  0.0  0.3  52680 13276 ?        S    12:33   0:00 /usr/bin/perl -w /usr/bin/prove --ext .rakutest --ext .t --ext .t6 -r -e /opt/rakudo-pkg/bin/rakudo t
hgwrqwo+  31724  0.3  2.8 596140 115116 ?       Sl   12:33   2:08 /opt/rakudo-pkg/bin/rakudo t/01-basic.t
root      32366  0.0  0.0  11876  1496 ?        Ss   21:19   0:00 sh /root/.sparrowdo/env/1586899174/.sparrowdo/sparrowrun.sh
root      32379  0.5  4.2 567212 169408 ?       Sl   21:19   0:08 perl6 -MSparrow6::DSL sparrowfile
root      32942  0.0  0.0  15048  2332 pts/1    Ss+  21:20   0:00 /bin/bash
root      33005  0.0  0.0  11876  1640 ?        S    21:20   0:00 bash /root/.sparrow6/tmp/323794/2/cmd.bash
root      33028  0.0  0.0 100720  3168 ?        S    21:20   0:00 su --shell /usr/bin/bash --login -c   cd /home/bxxzyrrgur/.zef/store/Gcrypt-0.4.tar.gz/Gcrypt-0.4 && zef install . bxxzyrrgur
bxxzyrr+  33029  4.0  8.5 782000 343988 ?       Ssl  21:20   1:04 perl6 /opt/rakudo-pkg/bin/zef install .
bxxzyrr+  33471  0.0  0.3  52688 13284 ?        S    21:23   0:00 /usr/bin/perl -w /usr/bin/prove --ext .rakutest --ext .t --ext .t6 -r -e /opt/rakudo-pkg/bin/rakudo t
bxxzyrr+  33480  0.3  2.8 595728 115692 ?       Sl   21:23   0:05 /opt/rakudo-pkg/bin/rakudo t/01-basic.t
root      33494  0.0  0.0  43944  1700 ?        Rs   21:47   0:00 ps uax
```

**Comment by CurtTilmes** [comment]
I can replicate a hang in `gcry_get_config()` which is only used in test `01-basic.t`

I had previously seen some weird returns from that and had wrapped it in a `try {}` that makes the test always succeed on alpine and debian, but on centos is just hangs.

(Verion 0.5 just released has the `try`)

**Comment by CurtTilmes** [comment]
Is there a good CentOS docker with rakudo already installed?

I've been using this:
```
	docker run --rm -it \
	  -e RELEASE_TESTING=1 \
	  -e PERL6LIB=/test \
	  -v `pwd`:/test -w /test \
          --entrypoint="/bin/sh" \
	  centos:latest \
	  -c "yum install -y wget curl git && wget https://dl.bintray.com/nxadm/rakudo-pkg-rpms/CentOS/8/x86_64/rakudo-pkg-CentOS8-2020.02.1-04.x86_64.rpm && yum install -y rakudo-pkg-CentOS8-2020.02.1-04.x86_64.rpm && export PATH=/opt/rakudo-pkg/bin:$PATH && zef install --/test --deps-only --test-depends . && /bin/bash"
```

**Comment by CurtTilmes** [comment]
If I put a print right before and after this line calls `gcry_get_config`, the first one prints and the second one doesn't: 
https://github.com/CurtTilmes/raku-libgcrypt/blob/master/lib/Gcrypt.rakumod#L94
it seems to just hang.

**Comment by CurtTilmes** [comment]
If you remove that test, every other test succeeds and everything seems to work fine other than printing the config.

**Comment by melezhik** [comment]
> Is there a good CentOS docker with rakudo already installed?
> 
> I've been using this:
> 
> ```
> 	docker run --rm -it \
> 	  -e RELEASE_TESTING=1 \
> 	  -e PERL6LIB=/test \
> 	  -v `pwd`:/test -w /test \
>           --entrypoint="/bin/sh" \
> 	  centos:latest \
> 	  -c "yum install -y wget curl git && wget https://dl.bintray.com/nxadm/rakudo-pkg-rpms/CentOS/8/x86_64/rakudo-pkg-CentOS8-2020.02.1-04.x86_64.rpm && yum install -y rakudo-pkg-CentOS8-2020.02.1-04.x86_64.rpm && source ~/.bashrc && zef install --/test --deps-only --test-depends . && /bin/bash"
> ```

The things is you can run tests right from RakuDist, you can even point your GitHub repo!


http://repo.westus.cloudapp.azure.com/rakudist

**Comment by CurtTilmes** [comment]
I'm just going to remove the config test and add a note to README that `.config` may not work on CentOS.

**Comment by CurtTilmes** [comment]
Just uploaded a version 0.6 without the config test.

**Comment by melezhik** [comment]
this is how you test against Centos:

`curl -d os=centos -d project=CurtTilmes/raku-libgcrypt http://repo.westus.cloudapp.azure.com/rakudist/api/run/:github`

**Comment by melezhik** [comment]
looks good!

![gcrypt success](https://raw.githubusercontent.com/melezhik/images/master/gcrypt.png)

**Comment by melezhik** [comment]
http://repo.westus.cloudapp.azure.com/rakudist/reports/CurtTilmes/raku-libgcrypt/centos/1586903594.txt
